package com.example.Backend.repository;

import com.example.Backend.entity.Report;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

@Repository
public interface ReportRepository extends JpaRepository<Report, UUID> {

    /**
     * Find reports by type
     */
    List<Report> findByReportType(String reportType);

    /**
     * Find reports by type with pagination (sorted by most recent)
     */
    Page<Report> findByReportTypeOrderByCreatedAtDesc(String reportType, Pageable pageable);

    /**
     * Find reports generated by a specific admin
     */
    List<Report> findByGeneratedBy(UUID adminId);

    /**
     * Find reports generated between dates
     */
    List<Report> findByCreatedAtBetween(LocalDateTime startDate, LocalDateTime endDate);

    /**
     * Find recent reports (last N days)
     */
    @Query("SELECT r FROM Report r WHERE r.createdAt >= :since ORDER BY r.createdAt DESC")
    List<Report> findRecentReports(@Param("since") LocalDateTime since);

    /**
     * Find all reports sorted by creation date
     */
    @Query("SELECT r FROM Report r ORDER BY r.createdAt DESC")
    Page<Report> findAllReportsSortedByDate(Pageable pageable);

    /**
     * Find reports with file exports (CSV/PDF)
     */
    @Query("SELECT r FROM Report r WHERE r.fileUrl IS NOT NULL ORDER BY r.createdAt DESC")
    List<Report> findReportsWithFiles();

    /**
     * Search reports by title or description
     */
    @Query("SELECT r FROM Report r WHERE " +
            "LOWER(r.title) LIKE LOWER(CONCAT('%', :searchTerm, '%')) OR " +
            "LOWER(r.description) LIKE LOWER(CONCAT('%', :searchTerm, '%'))")
    List<Report> searchReports(@Param("searchTerm") String searchTerm);

    /**
     * Count reports by type
     */
    Long countByReportType(String reportType);

    /**
     * Count reports generated by admin
     */
    Long countByGeneratedBy(UUID adminId);

    /**
     * Get latest report of a specific type
     */
    @Query("SELECT r FROM Report r WHERE r.reportType = :reportType ORDER BY r.createdAt DESC LIMIT 1")
    Report findLatestReportByType(@Param("reportType") String reportType);
}
